# Generated by Django 5.2.6 on 2025-10-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_brand_product_productimage_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_list',
            new_name='is_listed',
        ),
    ]
