# Generated by Django 5.2.6 on 2025-10-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='main_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants_using_as_main_offer', to='adminpanel.offer'),
        ),
    ]
