# Generated by Django 5.2.6 on 2025-10-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_variant_main_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='main_offer',
        ),
    ]
