# Generated by Django 5.2.6 on 2025-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_variant_main_offer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'category'), name='unique_product_per_brand_category'),
        ),
    ]
