# Generated by Django 5.2.6 on 2025-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
