# Generated by Django 5.2.6 on 2025-11-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_signupuserotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupuserotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
