# Generated by Django 5.2.6 on 2025-11-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Maximum usage count')),
                ('max_redeemable_price', models.DecimalField(decimal_places=2, default=0.0, help_text='max discount amount', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum purchase to apply coupon', max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount percentage ')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
