# Generated by Django 5.2.6 on 2025-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_product_unique_product_per_brand_category'),
        ('cart', '0002_cartitem_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='unique_product_per_cart_variant'),
        ),
    ]
