# Generated by Django 5.2.6 on 2025-11-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_razorpay_order_id_wallettransaction_razorpay_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='razorpay_transaction_id',
            new_name='razorpay_order_id',
        ),
    ]
