# Generated by Django 5.2.6 on 2025-11-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_razorpay_transaction_id_wallettransaction_razorpay_order_id'),
        ('orders', '0013_order_coupon_amount_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_order', to='orders.order'),
        ),
    ]
