# Generated by Django 5.2.6 on 2025-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_reason_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
