# Generated by Django 5.2.6 on 2025-11-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_is_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='item',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order'),
        ),
    ]
