# Generated by Django 5.2.6 on 2025-11-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_code_order_coupon_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='code',
            new_name='coupon_code',
        ),
    ]
