# Generated by Django 5.2.6 on 2025-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_code_order_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
