# Generated by Django 5.2.6 on 2025-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_coupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
