# Generated by Django 5.2.6 on 2025-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_amount_static',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
