# Generated by Django 5.2.6 on 2025-11-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_returnrequest_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order'),
        ),
    ]
