# Generated by Django 5.2.6 on 2025-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_returnitemrequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='returnitemrequest',
            constraint=models.UniqueConstraint(fields=('order', 'order_item'), name='unique_order_per_order_item'),
        ),
    ]
