# Generated by Django 5.2.6 on 2025-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_returnitemrequest_unique_order_per_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
