# Generated by Django 5.2.6 on 2025-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderitem_is_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
