# Generated by Django 5.2.6 on 2025-11-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_product_unique_product_per_brand_category'),
        ('products', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlistitem',
            name='unique_product_variant_per_wishlist',
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'product'), name='unique_product_variant_per_wishlist'),
        ),
    ]
